---
version: '3.8'
name: chat_rpg

services:
  redis:
    container_name: redis-rpg
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - rpg-network
  mongodb:
    container_name: mongo-rpg
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./src/config/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo-data:/data/db
    networks:
      - rpg-network
    env_file:
      - .env
  api:
    container_name: api-rpg
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # exemplo de envinronment
    environment:
      PORT: 5000
      HOST: localhost
      JWT_SECRET: secret
      JWT_EXPIRATION_TIME: 12h
      CRYPTO_SALT: salt
      CRYPTO_ITERATIONS: 10
      CRYPTO_KEY_LENGTH: 64
      CRYPTO_DIGEST: sha512
      MONGO_INITDB_DATABASE: chatrpg
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_PORT: 27017
      MONGO_HOST: mongo-rpg
      REDIS_HOST: redis-rpg
      REDIS_PORT: 6379
    depends_on:
      - redis
      - mongodb
    ports:
      - 5000:5000
      - 5001:5001
    networks:
      - rpg-network

volumes:
  mongo-data:
    external: false
  redis-data:
    external: false
networks:
  rpg-network:
    driver: bridge
    external: false
